In [1]:
import numpy as np
import pandas as pd

In [2]:
X = [[1], [2], [3], [4], [5], [6]]

In [3]:
y = [1,2,3,4,5,6]

In [5]:
X = np.array(X)
y = np.array(y)

In [7]:
indices = np.arange(len(X))

In [8]:
np.random.seed(42)
np.random.shuffle(indices)

In [9]:
indices

array([0, 1, 5, 2, 4, 3])

In [10]:
test_count = int(len(X)*0.33)

In [11]:
test_indices = indices[:test_count]

In [12]:
test_indices

array([0])

In [16]:
X[[3,2,5,1, 0]]

array([[4],
       [3],
       [6],
       [2],
       [1]])

In [5]:
df = pd.read_csv("/data2/mainaksaha/000_Model_Building/data/Advertising.csv")

In [6]:
from mklearn.linear_model import Lasso
from mklearn.model_selection import train_test_split
from mklearn.preprocessing import StandardScaler
from mklearn.svm import SVC

In [7]:
df.head()

TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [8]:
df.shape

(200, 4)

In [9]:
X = df.drop('Sales', axis=1)
y = df['Sales']

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=32)

In [11]:
scaler = StandardScaler()

In [12]:
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [13]:
model =  Lasso(learning_rate=0.0025, n_iterations=5000, alpha=0.9)

In [14]:
model.fit(X_train, y_train)

In [15]:
y_pred = model.predict(X_test)

In [16]:
y_pred

array([13.72606854,  9.71094672, 13.45403419, 23.07610679,  9.14900587,
       11.73926592, 10.10537659, 19.61391591,  7.81130574,  6.56009468,
       17.19472153, 13.97819104, 20.6560005 , 16.66940971, 12.3122253 ,
       12.1009635 ,  7.12657548, 23.32347504, 19.99278575, 15.48773101,
       15.24029273,  8.87620541, 14.8144284 , 14.30761075,  8.9241933 ,
        8.75426326,  8.58435161, 18.88729943,  9.74087874,  9.91472744,
       11.27140556, 10.10613923, 17.76660626, 15.53721989, 12.78969584,
       18.34622829, 12.96671193, 13.86309166, 10.72853012,  7.6875776 ,
       15.49577298, 15.73269949, 18.40027106, 12.96550498, 21.11685923,
       16.6299259 , 19.15616626, 18.15069299, 24.16354512, 18.53336102,
       11.75279454,  6.4330037 , 11.80674967,  9.82449328, 17.17098639,
       15.08758854,  6.6352209 , 12.94501653, 11.37988726, 15.49786259])

In [20]:
np.sqrt((y_test-y_pred).dot(y_test-y_pred) )

np.float64(15.014274851849915)

In [21]:
y_test

array([11.6, 10.3, 12.2, 23.8, 10.5,  8.7, 11.4, 18.9,  7. ,  8.7, 15.9,
       12.2, 21.5, 15.5,  9.3, 11.7,  8.7, 24.4, 19.8, 15.9, 15. , 10.6,
       12.5, 14.4,  8.5, 10.4,  5.5, 15.9, 11. , 11. , 11.9, 11.3, 14.8,
       12.7, 11.7, 19.2, 12.6, 11.5,  1.6,  9.5, 15.3, 15.6, 19. , 12.8,
       22.6, 15.9, 17.4, 15. , 26.2, 19. ,  9.5,  5.6, 12. , 10.3, 17.1,
       15.2,  9.4, 13.2, 11.9, 15.5])

In [2]:
t = np.array([1,2,3,4])

In [3]:
t.dot(t)

np.int64(30)

In [4]:
t.T.dot(t)

np.int64(30)