In [1]:
import numpy as np
import pandas as pd

In [2]:
X = [[1], [2], [3], [4], [5], [6]]

In [3]:
y = [1,2,3,4,5,6]

In [5]:
X = np.array(X)
y = np.array(y)

In [7]:
indices = np.arange(len(X))

In [8]:
np.random.seed(42)
np.random.shuffle(indices)

In [9]:
indices

array([0, 1, 5, 2, 4, 3])

In [10]:
test_count = int(len(X)*0.33)

In [11]:
test_indices = indices[:test_count]

In [12]:
test_indices

array([0])

In [16]:
X[[3,2,5,1, 0]]

array([[4],
       [3],
       [6],
       [2],
       [1]])

In [2]:
df = pd.read_csv("/data2/mainaksaha/000_Model_Building/data/Advertising.csv")

In [3]:
from mklearn.linear_model import LinearRegression
from mklearn.model_selection import train_test_split
from mklearn.preprocessing import StandardScaler

In [4]:
df.head()

TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [5]:
df.shape

(200, 4)

In [6]:
X = df.drop('Sales', axis=1)
y = df['Sales']

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=32)

In [16]:
scaler = StandardScaler()

In [17]:
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [18]:
model =  LinearRegression(learning_rate=0.01, n_itenations=5000)

In [19]:
model.fit(X_train, y_train)

In [20]:
y_pred = model.predict(X_test)

In [21]:
np.sqrt((y_test-y_pred).T.dot(y_test-y_pred))/len(y_test)

0.24998401181638902

In [22]:
y_train

array([18. ,  8.6, 24.7, 16.6,  7.2, 20.7, 18. , 13.4,  9.2,  9.7, 16. ,
       12.5, 17.3, 22.2, 23.7, 23.8, 10.1, 17.1, 14.9, 25.5, 21.4, 14.6,
       20.8,  7.3, 14.7,  5.3, 25.4, 11.6,  8.4, 23.2, 10.4, 20.2, 22.4,
       11.8, 12.2, 14. , 22.3,  5.7, 13.6,  3.2, 14.8,  9.7, 14.6, 13.3,
        9.9, 19.4, 12.6,  8.1, 18.4,  4.8, 14.7,  9.5,  8.8, 10.9, 15.2,
       17.2, 17.6, 14.1, 27. ,  5.9, 10.9, 10.1,  9.6,  8.8, 16.9,  6.6,
       19.6, 10.5,  6.7,  9.7, 13.2,  7.2, 18.3, 13.2,  6.9,  9.7, 16.1,
       21.2,  5.3,  6.6, 22.1, 10.7, 10.6, 20.1, 12. , 11.8, 11.6, 12.3,
       21.7, 18.9, 19.2, 25.4, 13.4, 11.9, 21.8, 16.6, 12.9, 24.2, 17. ,
       11.4,  7.3,  7.6, 11.5, 13.4, 10.8, 14.5, 18. , 11.2, 22.6, 10.1,
       15.5, 17.3, 15.7, 17.4, 14.2,  8. , 11.7, 11.7, 11.8,  9.6, 11.3,
       20.7,  9.7, 12.8, 14.9,  9.3,  7.6, 20.7, 12.9, 10.6, 18.5, 16.7,
       12.4, 25.4, 12.9, 10.8, 19.7, 20.2, 19.6, 12.9])

In [23]:
df['Sales']

0      22.1
1      10.4
2       9.3
3      18.5
4      12.9
       ... 
195     7.6
196     9.7
197    12.8
198    25.5
199    13.4
Name: Sales, Length: 200, dtype: float64