In [1]:
import numpy as np
import pandas as pd

In [2]:
X = [[1], [2], [3], [4], [5], [6]]

In [3]:
y = [1,2,3,4,5,6]

In [5]:
X = np.array(X)
y = np.array(y)

In [7]:
indices = np.arange(len(X))

In [8]:
np.random.seed(42)
np.random.shuffle(indices)

In [9]:
indices

array([0, 1, 5, 2, 4, 3])

In [10]:
test_count = int(len(X)*0.33)

In [11]:
test_indices = indices[:test_count]

In [12]:
test_indices

array([0])

In [16]:
X[[3,2,5,1, 0]]

array([[4],
       [3],
       [6],
       [2],
       [1]])

In [2]:
df = pd.read_csv("/data2/mainaksaha/000_Model_Building/data/hearing_test.csv")

In [10]:
from mklearn.linear_model import LogisticRegression
from mklearn.model_selection import train_test_split
from mklearn.preprocessing import StandardScaler
from mklearn.svm import SVC

In [4]:
df.head()

age  physical_score  test_result
0  33.0            40.7            1
1  50.0            37.2            1
2  52.0            24.7            0
3  56.0            31.0            0
4  35.0            42.9            1

In [5]:
df.shape

(5000, 3)

In [6]:
X = df.drop('test_result', axis=1)
y = df['test_result']

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=32)

In [8]:
scaler = StandardScaler()

In [9]:
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [11]:
model =  SVC(learning_rate=0.0025, n_iterations=5000, C=0.9)

In [12]:
model.fit(X_train, y_train)

In [13]:
y_pred = model.predict(X_test)

In [14]:
y_pred

array([1, 1, 1, ..., 1, 1, 0])

In [15]:
(y_test-y_pred).T.dot(y_test-y_pred)

np.int64(337)

In [19]:
y_test

array([1, 0, 1, ..., 1, 1, 0])